### ISSUE TITLE
Use headless mc instead of headless forge

### ISSUE THREAD

**Issue by NateKomodo** [nothub/headlessbot-old#31]
Headless Forge is now deprecated in favour of https://github.com/3arthqu4ke/HeadlessMc

This repo should be updated to use it

**Comment by nothub** [comment]
:ok_hand: I probably gonna archive this at some point and start a new project from scratch for wrapping hmc.

**Comment by nothub** [comment]
@NateKomodo I finally got around starting the port, new repo will live here: https://github.com/nothub/headlessbot
